### ISSUE TITLE
Issues with XSD

### ISSUE THREAD

**Issue by sachinSargar** [kadaster/klic-win#40]
XSD issue’s
• We have converted the XSD ‘IMKL2015-wion.xsd’ to C# classes using Xsd2Code tool of Visual studio.
• It got converted to C# classes.
• But when we try to serialize the class (for example FeatureCollecton) using.NET API it throws Invalid Operation error. Refer below image.

![image](https://cloud.githubusercontent.com/assets/22631958/19104629/59838d22-8afb-11e6-829e-ea36b8abf2f7.png)

• When we go into the details of the error it shows ‘Cannot serialize object of type 'IMKL2015_wion.MeasureType'. Consider changing type of XmlText member 'IMKL2015_wion.MeasureType.Value' from System.Double to string or string array’ 
• From the above description of error, we understand that for serializing or converting to XML the type must be in string , but in the XSD it is double.
• We changed the type(Double to string) of the property, then we noticed that it requires changes in more than one places. Then we changed all the classes that are generated from XSD. Changes was required in around 126 places in the classes.
• After doing the above changes, we got another error. Refer below image 

• The error showed ‘Type of choice identifier 'ItemsElementName' is inconsistent with type of 'Items'. Please use array of System.Collections.Generic.List`1[[IMKL2015_wion.ItemsChoiceType3, IMKL2015-wion, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].’
• Above error was because of the itemchoices are in LIST datatypes they must be array. 

![invalid2](https://cloud.githubusercontent.com/assets/22631958/19104811/2efb264a-8afc-11e6-8f05-92af73f6d4bd.jpg)

**Comment by mvvaalen** [comment]
On behalf of Stephan (KPN), I have added some additional information to this issue
Regards 

# Martin (KPN)

Hi,

## I have done the same as you but the error I’m getting is very dependent on the settings I choose for the Xsd2Code tool:

1 Settings:
![issue-40-pic1](https://cloud.githubusercontent.com/assets/22219152/19115644/104afca4-8b13-11e6-9d48-a3c7419cad98.PNG)
Error Message:

## There was an error reflecting type 'WindowsFormsApplication1.LinearRingType'. ---> System.InvalidOperationException: There was an error reflecting property 'Items'. ---> System.InvalidOperationException: There was an error reflecting type 'WindowsFormsApplication1.DirectPositionType'. ---> System.InvalidOperationException: There was an error reflecting property 'Text'. ---> System.InvalidOperationException: Member 'Text' cannot be encoded using the XmlText attribute. You may use the XmlText attribute to encode primitives, enumerations, arrays of strings, or arrays of XmlNode.

2 Settings:
![issue-40-pic2](https://cloud.githubusercontent.com/assets/22219152/19115997/41036092-8b14-11e6-9b3d-1543090d1dad.PNG)

Error Message:
System.InvalidOperationException: There was an error reflecting type 'WindowsFormsApplication1.FeatureCollectionType'. ---> System.InvalidOperationException: There was an error reflecting type 'WindowsFormsApplication1.ImageCRSType'. ---> System.InvalidOperationException: There was an error reflecting type 'WindowsFormsApplication1.ConcatenatedOperationType'. ---> System.InvalidOperationException: There was an error reflecting property 'domainOfValidity'. ---> System.InvalidOperationException: There was an error reflecting type 'WindowsFormsApplication1.domainOfValidity'. ---> System.InvalidOperationException: There was an error reflecting property 'EX_Extent'. ---> System.InvalidOperationException: There was an error reflecting type 'WindowsFormsApplication1.EX_Extent_Type'. ---> System.InvalidOperationException: There was an error reflecting type 'WindowsFormsApplication1.AbstractMD_ContentInformation_Type'. ---> System.InvalidOperationException: There was an error reflecting type 'WindowsFormsApplication1.MD_CoverageDescription_Type'. ---> System.InvalidOperationException: There was an error reflecting property 'dimension'. ---> System.InvalidOperationException: There was an error reflecting type 'WindowsFormsApplication1.MD_RangeDimension_PropertyType'. ---> System.InvalidOperationException: There was an error reflecting property 'MD_RangeDimension'. ---> System.InvalidOperationException: There was an error reflecting type 'WindowsFormsApplication1.MD_RangeDimension_Type'. ---> System.InvalidOperationException: There was an error reflecting type 'WindowsFormsApplication1.MD_Band_Type'. ---> System.InvalidOperationException: There was an error reflecting property 'units'. ---> System.InvalidOperationException: There was an error reflecting type 'WindowsFormsApplication1.UomLength_PropertyType'. ---> System.InvalidOperationException: There was an error reflecting property 'UnitDefinition'. ---> System.InvalidOperationException: There was an error reflecting type 'WindowsFormsApplication1.UnitDefinitionType'. ---> System.InvalidOperationException: There was an error reflecting type 'WindowsFormsApplication1.ConventionalUnitType'. ---> System.InvalidOperationException: There was an error reflecting property 'Item'. ---> System.InvalidOperationException: Type WindowsFormsApplication1.ItemChoiceType is missing enumeration value 'Item' for element 'Item' from namespace ''.

---

The error I got with the second setting was caused by the following piece of code :

![issue-40-pic3](https://cloud.githubusercontent.com/assets/22219152/19115935/15c1a632-8b14-11e6-875a-fd03d65beb69.PNG)

Uncommenting this out got me the same error as you. I don’t know what exactly the error was, and trying to serialize a different type got the same error. 

Maybe Kadaster can generate a C# class for us ? Or maybe they can send us their java-generated class, then we can convert this to C# and see what happens.

Regards, Stephan

**Comment by martinborgman** [comment]
The problem you have is that the IMKL2015-wion.xsd depends on a very large number of other XSD's.
Generating code for only those classes you actually need is almost impossible using the tools we have.
This is part of the reason we didn't pursue this option.

One of the other reasons is that we don't need to completely serialize a XML feature into a Java object. We only need a small part of the information for what we need to do.

I hope that other developers are willing to share their experience and maybe even part of their code.

**Comment by GustavAT** [comment]
My answer is probably too late but it may help people who encounter similar problems in the future.

Xsd2Code might be feasible for smaller, rather simple XSDs, however it fails to generate proper classes for complex schemas i.e. IMKL2015. One problem is that it depends on the `XmlSerializer` class which does not support substitution groups (this schmema and its dependencies to INSPIRE have a lot of them). More infos in the FAQ section [here](https://docs.microsoft.com/en-us/dotnet/standard/serialization/controlling-xml-serialization-using-attributes). Furthermore it cannot serialize some GML types correctly i.e. `gml:posList` which contains a list of doubles separated by spaces.

I managed to generate C# classes using [Altova's XmlSpy](https://www.altova.com/xmlspy-xml-editor/xml-code-generation ). It uses its own implementation for serializing/traversing XML but all samples files could successfully deserialized.

**Comment by herman-vandenberg** [comment]
Thank you for sharing your experiences! As you know, our IMKL-model is based on INSPIRE- and gml-schema's which we cannot influence.
