### ISSUE TITLE
EigenTopographie missing links from Belanghebbende (Samples, Production)

### ISSUE THREAD

**Issue by adam-ludera-intive** [kadaster/klic-win#70]
As per direct, email communication with Kadaster in May 2019 we were informed that Kadaster will not be delivering their own Topography layers just yet (i.e. not in 2019), i.e. the layers delivered in pre-January 2019 delivery as GP_ files.

Therefore, we are expecting that all EigenTopographie layers will be linked with Utility Companies. Based on the Dataspecification document, if the EigenTopographie is coming from the Utility Company they should be linked from Belanghebbende by property eigenTopografie (0-N). 

However, in all the provided samples, as well as in production KLICs, we are finding EigenTopografie elements that are not linked from Belanghebbende. This is incorrect and must be fixed, otherwise, they are not fully usable.

Examples:
KLIC: 19O900151 - gml:id="nl.imkl-TS1392.BGI_brug-b"
KLIC: 19G502473 - gml:id="nl.imkl-KL1040.TOPO_Overig_Lijnvorming_object_tijdelijk15285_22779152"
KLIC: 19C000837 - gml:id="nl.imkl-KL1040.TOPO_As_Maatvoering734066078_32563779"

**Comment by herman-vandenberg** [comment]
Thanks for your attention.
Based on your examples, we have found that the reference from _Belanghebbende_ to _EigenTopografie_ is indeed missing in the deliveries: 19O900151 and 19G502473.
Example 19C000837 dates from January 2019 and can no longer be viewed by us.

Because the examples 19O900151 and 19O900152 are sample deliveries which are manually prepared by us, we have adjusted these accordingly. The new examples will be published on GitHub as soon as possible.
At the moment we are checking whether our software needs to be expanded to add these references to central network operators. For decentralized network operators, we currently do not check whether these references are filled correctly.

**Comment by herman-vandenberg** [comment]
We have adjusted our KLIC-system in such a way that all supplied _EigenTopografie_-objects are referred to by the object _Belanghebbende_.
These references are built up for both decentralized and central network operators.
(internal reference: https://dev.kadaster.nl/jira/browse/KLCW-5004)
